# If you only want a lightweight installation of xiaozhi-server and only use local configuration files, you don't need to pay attention to this file, no need to change anything in this file
# If you want to get configuration from manager-api, please read below:
# Please copy this file to the xiaozhi-server/data directory, if there is no data directory, please create one, and rename the copied file to .config.yaml
# Note: if the data directory already has a .config.yaml file, please delete it first
# First start manager-api and manager-web, register an account, the first registered account will be the administrator
# Use the administrator account, enter the [Parameter Management] page, find [server.secret], copy its parameter value, note that server.secret changes every time you deploy from scratch
# Open the .config.yaml file in this data directory, modify manager-api.secret to the server.secret you just copied
server:
  ip: 0.0.0.0
  port: 8000
  # HTTP service port, used for vision analysis interface
  http_port: 8003
  # Vision analysis interface address
  # Vision analysis interface address sent to devices
  # If using the default writing below, the system will automatically generate the vision recognition address and output it in the startup log, you can directly access this address with a browser to confirm
  # When you use docker deployment or public network deployment (using SSL, domain name), it may not be accurate
  # So if you use docker deployment, set vision_explain to the LAN address
  # If you use public network deployment, set vision_explain to the public network address
  vision_explain: http://your-ip-or-domain:port-number/mcp/vision/explain
manager-api:
  # Your manager-api address, preferably using LAN IP
  # If using docker deployment, please fill in as http://xiaozhi-esp32-server-web:8002/xiaozhi
  url: http://127.0.0.1:8002/xiaozhi
  # Your manager-api token, which is the server.secret you copied earlier
  secret: your-server.secret-value
