# Docker installation for Server only

version: '3'
services:
  xiaozhi-esp32-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    ports:
      # ws server
      - "8000:8000"
      # http service port, used for simple OTA interface (single service deployment) and visual analysis interface
      - "8003:8003"
    volumes:
      # Configuration file directory
      - ./data:/opt/xiaozhi-esp32-server/data
      # Model file mount, very important
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
